import { chromium } from 'file:///C:/Users/13306/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';

const base = process.env.YJ_BASE_URL || 'http://127.0.0.1:8765';
const result = { base, passed: [], failed: [], consoleErrors: [], timestamp: new Date().toISOString() };
const check = (name, ok, detail='') => (ok ? result.passed : result.failed).push({name, detail});
const browser = await chromium.launch({headless: true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror', e => result.consoleErrors.push(e.message));
await page.goto(base + '/demo/', {waitUntil:'domcontentloaded'});
check('Demo 页面可访问', (await page.title()).includes('云匠'), await page.title());
check('项目中心已加载', await page.locator('#yj-project-root').count() === 1);
await page.evaluate(() => { try { localStorage.clear(); } catch {} });
await page.reload({waitUntil:'domcontentloaded'});
check('项目中心首页可见', await page.locator('#yj-page-home.yj-page-active').isVisible().catch(() => false));
check('原登录页在项目中心模式下隐藏', !(await page.locator('#onboardingScreen').isVisible().catch(() => false)));
await page.locator('#yj-home-demo').click();
await page.waitForTimeout(200);
check('快速体验页面可打开', await page.locator('#yj-page-quickdemo.yj-page-active').isVisible().catch(() => false));
await page.evaluate(() => window.startQuickDemo());
await page.waitForTimeout(300);
check('评审快速入口已安装', await page.locator('#reviewLaunchpad').count() === 1);
check('取消创作入口已安装', await page.locator('#cancelCreationBtn').count() === 1);
check('风格包选择器已安装', await page.locator('.style-pack-btn').count() >= 4);
check('60秒零Token体验可运行', await page.locator('#runEvidencePanel.open').count() === 1);
check('Agent Run 证据已生成', await page.locator('#runEvidencePanel').innerText().then(t => /角色设定检查点/.test(t)));
check('三个检查点有演示证据', await page.locator('#runEvidencePanel').innerText().then(t => ['角色设定','剧情大纲','分集剧本'].every(x=>t.includes(x))));
check('快速演示覆盖17位专家', await page.locator('#evidenceExperts').innerText().then(t => t.trim() === '17'));
check('Session 已持久化', await page.evaluate(() => !!localStorage.getItem('yunjiang_active_session_v4')));
const caps = await page.evaluate(async () => (await fetch('/api/v1/capabilities')).json());
check('能力清单为17 Agents/Skills', caps.agents === 17 && caps.skills === 17, JSON.stringify(caps));
const skills = await page.evaluate(async () => (await fetch('/api/v1/skills')).json());
check('Skills API 返回17项', skills.count === 17);
check('页面无未捕获JS错误', result.consoleErrors.length === 0, result.consoleErrors.join('; '));
await page.screenshot({path:'tests/final-demo-screenshot.png', fullPage:false});
await browser.close();
fs.writeFileSync('tests/browser-acceptance.json', JSON.stringify(result, null, 2));
console.log(JSON.stringify(result, null, 2));
if (result.failed.length) process.exit(1);

