import { chromium } from 'file:///C:/Users/13306/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import fs from 'node:fs';

const base = process.env.YJ_BASE_URL || 'http://127.0.0.1:8765';
const result = { base, passed: [], failed: [], consoleErrors: [], timestamp: new Date().toISOString() };
const check = (name, ok, detail='') => (ok ? result.passed : result.failed).push({name, detail});
const browser = await chromium.launch({headless: true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
page.on('pageerror', e => result.consoleErrors.push(e.message));
await page.goto(base + '/demo/', {waitUntil:'domcontentloaded'});
check('Demo 页面可访问', (await page.title()).includes('云匠'), await page.title());
check('项目中心已加载', await page.locator('#yj-project-root').count() === 1);
await page.evaluate(() => { try { localStorage.clear(); } catch {} });
await page.reload({waitUntil:'domcontentloaded'});
check('首次访问显示原登录页', await page.locator('#onboardingScreen').isVisible().catch(() => false));
check('未登录时项目中心隐藏', !(await page.locator('#yj-project-root').isVisible().catch(() => false)));
await page.locator('#creatorName').fill('验收创作者');
await page.evaluate(() => window.enterStudio());
await page.waitForTimeout(100);
check('登录后项目中心首页可见', await page.locator('#yj-page-home.yj-page-active').isVisible().catch(() => false));
check('登录后原登录页隐藏', !(await page.locator('#onboardingScreen').isVisible().catch(() => false)));
await page.locator('#yj-nav-account-btn').click();
await page.waitForTimeout(100);
check('切换创作者可返回登录页', await page.locator('#onboardingScreen').isVisible().catch(() => false));
check('退出不删除创作者名称', await page.locator('#creatorName').inputValue().then(value => value === '验收创作者'));
await page.evaluate(() => window.enterStudio());
await page.waitForTimeout(100);
await page.evaluate(() => {
  const original = window.startQuickDemo;
  window.startQuickDemo = options => original({ ...(options || {}), instant: true });
});
await page.locator('#yj-home-demo').click();
await page.waitForFunction(() => window.__yjQuickDemoPromise, null, {timeout:10000});
await page.evaluate(() => window.__yjQuickDemoPromise);
check('快速体验点击后进入工作台', await page.locator('.app-container').isVisible().catch(() => false));
check('核心运行进度完成', await page.locator('#yj-core-demo-status').innerText().then(t => t.includes('运行完成')));
check('实时进度显示4/4', await page.locator('#alsCount').innerText().then(t => t.replace(/\s/g, '') === '4/4'));
check('生成故事大纲、人物小传、集纲和正文', await page.locator('[data-demo-core]').count().then(n => n === 4));
check('评审快速入口已安装', await page.locator('#reviewLaunchpad').count() === 1);
check('取消创作入口已安装', await page.locator('#cancelCreationBtn').count() === 1);
check('风格包选择器已安装', await page.locator('.style-pack-btn').count() >= 4);
check('零Token体验可运行', await page.locator('#yj-core-demo-runner').innerText().then(t => t.includes('零 Token')));
check('Agent Run 证据已生成', await page.locator('#runEvidencePanel').innerText().then(t => ['故事大纲','人物小传','集纲','正文剧本'].every(x=>t.includes(x))));
check('核心演示启用4位以上专家', await page.locator('#evidenceExperts').innerText().then(t => Number(t.trim()) >= 4));
check('Session 已持久化', await page.evaluate(() => !!localStorage.getItem('yunjiang_active_session_v4')));
const caps = await page.evaluate(async () => (await fetch('/api/v1/capabilities')).json());
check('能力清单为17 Agents/Skills', caps.agents === 17 && caps.skills === 17, JSON.stringify(caps));
const skills = await page.evaluate(async () => (await fetch('/api/v1/skills')).json());
check('Skills API 返回17项', skills.count === 17);
check('页面无未捕获JS错误', result.consoleErrors.length === 0, result.consoleErrors.join('; '));
await page.screenshot({path:'tests/final-demo-screenshot.png', fullPage:false});
await browser.close();
fs.writeFileSync('tests/browser-acceptance.json', JSON.stringify(result, null, 2));
console.log(JSON.stringify(result, null, 2));
if (result.failed.length) process.exit(1);
